---
- name: Rodando....
  hosts: all
  become: yes

  tasks:

  - name: Install SDKMAN
    cmd: curl -s "https://get.sdkman.io" | bash && source "$HOME/.sdkman/bin/sdkman-init.sh"
    become: yes
    args:
      warn: False
  
  - name: Add Docker GPG key
    apt_key: 
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
      state: present

  - name: Add VSCode ASC key 
    apt_key: 
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present
  
  - name: Add VSCode repository
    apt_repository:
      repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
      state: present

  - name: Add Node repository
    shell: curl -sL https://deb.nodesource.com/setup_{{ node_version }}.x | bash -
    become: yes
    vars:
      node_version: 16
    args:
      warn: False

  - name: Install Stack
    apt: 
      name: "{{ item }}"
      update-cache: yes
      force_apt_get: yes
      state: latest
    with_items:
      - terminator
      - zsh
      - git
      - maven
      - apt-transport-https
      - ca-certificates
      - curl
      - wget
      - software-properties-common
      - docker-ce
      - docker-compose
      - nodejs
      - code
      - snapd 
      - snapd-xdg-open
    become: yes
  
  - name: Install Ohmyzsh
    shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    become: yes
    args:
      warn: False